USERNAME := $(shell whoami)

delete-labels:
	rm -rf /scratch/sfberrio/FLIR_ADAS_1_3/val/yolo_labels_$(USERNAME)/
	rm -rf /scratch/sfberrio/FLIR_ADAS_1_3/train/yolo_labels_$(USERNAME)/

delete-mini:
	rm -rf /scratch/sfberrio/FLIR_ADAS_1_3/val/thermal_8_bit_mini_$(USERNAME)/
	rm -rf /scratch/sfberrio/FLIR_ADAS_1_3/train/thermal_8_bit_mini_$(USERNAME)/
