

delete-labels:
	rm -rf /scratch/sfberrio/FLIR_ADAS_1_3/val/yolo_labels/
	rm -rf /scratch/sfberrio/FLIR_ADAS_1_3/train/yolo_labels/

delete-mini:
	rm -rf /scratch/sfberrio/FLIR_ADAS_1_3/val/thermal_8_bit_mini/
	rm -rf /scratch/sfberrio/FLIR_ADAS_1_3/train/thermal_8_bit_mini/
